-- 1. Create the 'reports' table if it doesn't exist
create table if not exists reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  "caseID" text unique not null,
  "busNumber" text,
  "incidentType" text,
  "incidentTime" text,
  description text,
  timestamp text,
  files jsonb default '[]'::jsonb,
  "fileCount" integer default 0,
  status text default 'SUBMITTED'
);

-- 2. Enable Row Level Security (RLS)
alter table reports enable row level security;

-- 3. Policies (Drop first to avoid errors if re-running)
drop policy if exists "Enable insert for everyone" on reports;
create policy "Enable insert for everyone" on reports for insert with check (true);

drop policy if exists "Enable read access for all" on reports;
create policy "Enable read access for all" on reports for select using (true);

drop policy if exists "Enable update for all" on reports;
create policy "Enable update for all" on reports for update using (true);

-- 4. Create Storage Bucket (Ignore if already exists)
insert into storage.buckets (id, name, public) 
values ('evidence', 'evidence', true)
on conflict (id) do nothing;

-- 5. Storage Policies (Drop first to avoid errors)
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using ( bucket_id = 'evidence' );

drop policy if exists "Public Upload" on storage.objects;
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'evidence' );
